# Generated by Django 4.2.5 on 2023-09-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
