# Generated by Django 4.2.5 on 2023-09-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_pregunta_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='alternativa2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='alternativa3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='alternativa4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
