# Generated by Django 4.2.5 on 2023-09-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_pregunta_alternativa2_pregunta_alternativa3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tema',
            field=models.CharField(choices=[('Diagramas de PVT', 'Diagramas de PVT'), ('Calidad de mezclas', 'Calidad de mezclas'), ('Entalpía', 'Entalpía'), ('Calor latente', 'Calor latente'), ('Tabla de saturación', 'Tabla de saturación')], max_length=50, null=True),
        ),
    ]
