# Generated by Django 4.2.5 on 2023-09-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_pregunta_hint_utilizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='hint_utilizado',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respondida_correctamente',
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_estudiante', models.CharField(max_length=255)),
                ('hint_utilizado', models.BooleanField(default=False)),
                ('respondida_correctamente', models.BooleanField(default=False)),
                ('pregunta_relacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='questions.pregunta')),
            ],
        ),
    ]
