# Generated by Django 4.2.5 on 2023-09-24 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_remove_pregunta_hint_utilizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='fecha_hora_respuesta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
