# Generated by Django 4.2.5 on 2023-09-24 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_respuesta_fecha_hora_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='tipo_pregunta',
            field=models.CharField(default=datetime.datetime(2023, 9, 24, 14, 49, 0, 942360, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
