# Generated by Django 4.2.5 on 2023-09-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_respuesta_tipo_pregunta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='hint_utilizado',
            new_name='uso_hint',
        ),
    ]
