# Generated by Django 4.2.5 on 2023-09-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_rename_hint_utilizado_respuesta_uso_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='tema',
            field=models.CharField(choices=[('Diagramas de PVT', 'Diagramas de PVT'), ('Calidad de mezclas', 'Calidad de mezclas'), ('Entalpía', 'Entalpía'), ('Calor latente', 'Calor latente'), ('Tabla de saturación', 'Tabla de saturación')], max_length=50, null=True),
        ),
    ]
