# Generated by Django 4.2.5 on 2023-09-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_userprofile_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nombre',
            field=models.CharField(default='juan', max_length=100),
            preserve_default=False,
        ),
    ]
