# Generated by Django 4.2.5 on 2023-09-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('questions', '0016_userprofile_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='CustomUser',
        ),
    ]
